use super::*;

#[test]
fn show_retainers() {
    let mut proc = McpProcess::start();
    load_heap1(&mut proc);

    let resp = proc.call_tool(
        2,
        "show_retainers",
        serde_json::json!({ "snapshot_id": 1, "object_id": "@7165" }),
    );
    let text = get_text(&resp);
    assert_eq!(
        text,
        r#"Object @7165: system / NativeContext (type: native, self_size: 1240, retained_size: 23708)
  <--[weak "value"]-- @21113 system / Cell (type: object shape, self_size: 8)
  <--[internal "context"]-- @20111 get disposed (type: closure, self_size: 28)
  <--[internal "context"]-- @20109 dispose (type: closure, self_size: 28)
  <--[internal "context"]-- @20107 use (type: closure, self_size: 28)
  <--[internal "context"]-- @19991 WebAssembly (type: closure, self_size: 32)
  <--[internal "context"]-- @19963  (type: closure, self_size: 28)
  <--[internal "context"]-- @19955 grow (type: closure, self_size: 28)
  <--[internal "context"]-- @19953 slice (type: closure, self_size: 28)
  <--[internal "context"]-- @19951 get growable (type: closure, self_size: 28)
  <--[internal "context"]-- @19949 get maxByteLength (type: closure, self_size: 28)
  <--[internal "context"]-- @19947 get byteLength (type: closure, self_size: 28)
  <--[internal "context"]-- @19923 get [Symbol.species] (type: closure, self_size: 28)
  <--[internal "context"]-- @19915 SetIterator (type: closure, self_size: 32)
  <--[internal "previous"]-- @19913 system / Context (type: object, self_size: 20)
  <--[internal "context"]-- @19911 next (type: closure, self_size: 28)
  <--[internal "context"]-- @19903 RegExpStringIterator (type: closure, self_size: 32)
  <--[internal "context"]-- @19891 MapIterator (type: closure, self_size: 32)
  <--[internal "context"]-- @19861 return (type: closure, self_size: 28)
  <--[internal "context"]-- @19859 next (type: closure, self_size: 28)
  <--[internal "context"]-- @19851 next (type: closure, self_size: 28)
  <--[internal "context"]-- @19843 Segment Iterator (type: closure, self_size: 32)
  <--[internal "context"]-- @19835 [Symbol.iterator] (type: closure, self_size: 28)
  <--[internal "context"]-- @19833 containing (type: closure, self_size: 28)
  <--[internal "context"]-- @19825 Segments (type: closure, self_size: 32)
  <--[internal "context"]-- @19821 next (type: closure, self_size: 28)
  <--[internal "context"]-- @19813 StringIterator (type: closure, self_size: 32)
  <--[internal "context"]-- @19811 next (type: closure, self_size: 28)
  <--[internal "context"]-- @19803 next (type: closure, self_size: 28)
  <--[internal "context"]-- @19795 return (type: closure, self_size: 28)
  <--[internal "context"]-- @19793 next (type: closure, self_size: 28)
  <--[internal "context"]-- @19787 next (type: closure, self_size: 28)
  <--[internal "context"]-- @19779 Array Iterator (type: closure, self_size: 32)
  <--[internal "context"]-- @19775 throw (type: closure, self_size: 28)
  <--[internal "context"]-- @19773 return (type: closure, self_size: 28)
  <--[internal "context"]-- @19771 next (type: closure, self_size: 28)
  <--[internal "context"]-- @19665 toResizableBuffer (type: closure, self_size: 28)
  <--[internal "context"]-- @19663 toFixedLengthBuffer (type: closure, self_size: 28)
  <--[internal "context"]-- @19661 promising (type: closure, self_size: 28)
  <--[internal "context"]-- @19645  (type: closure, self_size: 32)
  <--[internal "context"]-- @19643  (type: closure, self_size: 32)
  <--[internal "context"]-- @19641  (type: closure, self_size: 32)
  <--[internal "context"]-- @19633 getMessage (type: closure, self_size: 32)
  <--[internal "context"]-- @19631 postMessage (type: closure, self_size: 32)
  <--[internal "context"]-- @19629 terminateAndWait (type: closure, self_size: 32)
  <--[internal "context"]-- @19627 terminate (type: closure, self_size: 32)
  <--[internal "context"]-- @19621  (type: closure, self_size: 32)
  <--[internal "context"]-- @19619 is (type: closure, self_size: 28)
  <--[internal "context"]-- @19617 getArg (type: closure, self_size: 28)
  <--[internal "context"]-- @19615 set value (type: closure, self_size: 28)
  <--[internal "context"]-- @19613 get value (type: closure, self_size: 28)
  <--[internal "context"]-- @19611 valueOf (type: closure, self_size: 28)
  <--[internal "context"]-- @19609 get buffer (type: closure, self_size: 28)
  <--[internal "context"]-- @19607 grow (type: closure, self_size: 28)
  <--[internal "context"]-- @19605 get (type: closure, self_size: 28)
  <--[internal "context"]-- @19603 set (type: closure, self_size: 28)
  <--[internal "context"]-- @19601 grow (type: closure, self_size: 28)
  <--[internal "context"]-- @19599 get length (type: closure, self_size: 28)
  <--[internal "context"]-- @19597 get exports (type: closure, self_size: 28)
  <--[internal "context"]-- @19595 customSections (type: closure, self_size: 28)
  <--[internal "context"]-- @19593 exports (type: closure, self_size: 28)
  <--[internal "context"]-- @19591 imports (type: closure, self_size: 28)
  <--[internal "context"]-- @19589 instantiate (type: closure, self_size: 28)
  <--[internal "context"]-- @19587 validate (type: closure, self_size: 28)
  <--[internal "context"]-- @19585 compile (type: closure, self_size: 28)
  <--[internal "context"]-- @19581 Arguments (type: closure, self_size: 32)
  <--[internal "context"]-- @19575 setContinuationPreservedEmbedderData (type: closure, self_size: 28)
  <--[internal "context"]-- @19573 getContinuationPreservedEmbedderData (type: closure, self_size: 28)
  <--[internal "context"]-- @19571 trace (type: closure, self_size: 28)
  <--[internal "context"]-- @19569 isTraceCategoryEnabled (type: closure, self_size: 28)
  <--[internal "context"]-- @19549 toString (type: closure, self_size: 28)
  <--[internal "context"]-- @19547 isToplevel (type: closure, self_size: 28)
  <--[internal "context"]-- @19545 isPromiseAll (type: closure, self_size: 28)
  <--[internal "context"]-- @19543 isNative (type: closure, self_size: 28)
  <--[internal "context"]-- @19541 isEval (type: closure, self_size: 28)
  <--[internal "context"]-- @19539 isConstructor (type: closure, self_size: 28)
  <--[internal "context"]-- @19537 isAsync (type: closure, self_size: 28)
  <--[internal "context"]-- @19535 getTypeName (type: closure, self_size: 28)
  <--[internal "context"]-- @19533 getThis (type: closure, self_size: 28)
  <--[internal "context"]-- @19531 getScriptHash (type: closure, self_size: 28)
  <--[internal "context"]-- @19529 getScriptNameOrSourceURL (type: closure, self_size: 28)
  <--[internal "context"]-- @19527 getPromiseIndex (type: closure, self_size: 28)
  <--[internal "context"]-- @19525 getPosition (type: closure, self_size: 28)
  <--[internal "context"]-- @19523 getMethodName (type: closure, self_size: 28)
  <--[internal "context"]-- @19521 getLineNumber (type: closure, self_size: 28)
  <--[internal "context"]-- @19519 getFunctionName (type: closure, self_size: 28)
  <--[internal "context"]-- @19517 getFunction (type: closure, self_size: 28)
  <--[internal "context"]-- @19515 getFileName (type: closure, self_size: 28)
  <--[internal "context"]-- @19513 getEvalOrigin (type: closure, self_size: 28)
  <--[internal "context"]-- @19511 getEnclosingLineNumber (type: closure, self_size: 28)
  <--[internal "context"]-- @19509 getEnclosingColumnNumber (type: closure, self_size: 28)
  <--[internal "context"]-- @19507 getColumnNumber (type: closure, self_size: 28)
  <--[internal "context"]-- @19489 throw (type: closure, self_size: 28)
  <--[internal "context"]-- @19487 return (type: closure, self_size: 28)
  <--[internal "context"]-- @19485 next (type: closure, self_size: 28)
  <--[internal "context"]-- @19439 throw (type: closure, self_size: 28)
  <--[internal "context"]-- @19437 return (type: closure, self_size: 28)
  <--[internal "context"]-- @19435 next (type: closure, self_size: 28)
  <--[internal "context"]-- @19431 [Symbol.asyncDispose] (type: closure, self_size: 28)
  <--[internal "context"]-- @19429 [Symbol.asyncIterator] (type: closure, self_size: 28)
  <--[internal "context"]-- @19415 transferToFixedLength (type: closure, self_size: 28)
  (1-100 of 874 retainers shown)"#
    );
}

#[test]
fn show_retainers_with_depth() {
    let mut proc = McpProcess::start();
    load_heap1(&mut proc);

    // depth=1 should not have nested retainers
    let resp1 = proc.call_tool(
        2,
        "show_retainers",
        serde_json::json!({ "snapshot_id": 1, "object_id": "@7165" }),
    );
    let text1 = get_text(&resp1);
    let nested: Vec<_> = text1
        .lines()
        .filter(|l| l.starts_with("    <--["))
        .collect();
    assert!(
        nested.is_empty(),
        "depth=1 should not have nested retainers, got: {text1}"
    );

    // depth=2 should have nested retainers
    let resp2 = proc.call_tool(
        3,
        "show_retainers",
        serde_json::json!({ "snapshot_id": 1, "object_id": "@7165", "depth": 2 }),
    );
    let text2 = get_text(&resp2);
    assert_eq!(
        text2,
        r#"Object @7165: system / NativeContext (type: native, self_size: 1240, retained_size: 23708)
  <--[weak "value"]-- @21113 system / Cell (type: object shape, self_size: 8)
    <--[hidden "0"]-- @21121 system / Map (type: object shape, self_size: 40)
    <--[hidden "0"]-- @21119 system / Map (type: object shape, self_size: 40)
    <--[hidden "0"]-- @21115 system / Map (type: object shape, self_size: 40)
    <--[hidden "0"]-- @21107 system / Map (type: object shape, self_size: 40)
    <--[hidden "0"]-- @16789 system / Map (type: object shape, self_size: 40)
  <--[internal "context"]-- @20111 get disposed (type: closure, self_size: 28)
    <--[property "get disposed"]-- @20105 DisposableStack (type: object, self_size: 28)
    <--[internal "getter"]-- @16841 system / AccessorPair (type: native, self_size: 12)
  <--[internal "context"]-- @20109 dispose (type: closure, self_size: 28)
    <--[property "<symbol Symbol.dispose>"]-- @20105 DisposableStack (type: object, self_size: 28)
    <--[property "dispose"]-- @20105 DisposableStack (type: object, self_size: 28)
  <--[internal "context"]-- @20107 use (type: closure, self_size: 28)
    <--[property "use"]-- @20105 DisposableStack (type: object, self_size: 28)
  <--[internal "context"]-- @19991 WebAssembly (type: closure, self_size: 32)
    <--[internal "constructor"]-- @19999 system / Map (type: object shape, self_size: 40)
    <--[internal "constructor"]-- @19993 system / Map (type: object shape, self_size: 40)
  <--[internal "context"]-- @19963  (type: closure, self_size: 28)
    <--[internal "setter"]-- @19961 system / AccessorPair (type: native, self_size: 12)
    <--[internal "getter"]-- @19961 system / AccessorPair (type: native, self_size: 12)
  <--[internal "context"]-- @19955 grow (type: closure, self_size: 28)
    <--[property "grow"]-- @19929 SharedArrayBuffer (type: object, self_size: 28)
  <--[internal "context"]-- @19953 slice (type: closure, self_size: 28)
    <--[property "slice"]-- @19929 SharedArrayBuffer (type: object, self_size: 28)
  <--[internal "context"]-- @19951 get growable (type: closure, self_size: 28)
    <--[internal "getter"]-- @19945 system / AccessorPair (type: native, self_size: 12)
    <--[property "get growable"]-- @19929 SharedArrayBuffer (type: object, self_size: 28)
  <--[internal "context"]-- @19949 get maxByteLength (type: closure, self_size: 28)
    <--[internal "getter"]-- @19943 system / AccessorPair (type: native, self_size: 12)
    <--[property "get maxByteLength"]-- @19929 SharedArrayBuffer (type: object, self_size: 28)
  <--[internal "context"]-- @19947 get byteLength (type: closure, self_size: 28)
    <--[internal "getter"]-- @19941 system / AccessorPair (type: native, self_size: 12)
    <--[property "get byteLength"]-- @19929 SharedArrayBuffer (type: object, self_size: 28)
  <--[internal "context"]-- @19923 get [Symbol.species] (type: closure, self_size: 28)
    <--[internal "getter"]-- @19921 system / AccessorPair (type: native, self_size: 12)
    <--[property "<symbol Symbol.species>"]-- @16497 SharedArrayBuffer (type: closure, self_size: 32)
  <--[internal "context"]-- @19915 SetIterator (type: closure, self_size: 32)
    <--[internal "constructor"]-- @16495 system / Map (type: object shape, self_size: 40)
    <--[internal "constructor"]-- @16493 system / Map (type: object shape, self_size: 40)
  <--[internal "previous"]-- @19913 system / Context (type: object, self_size: 20)
    <--[hidden "1"]-- @7533 system / ScriptContextTable (type: native, self_size: 80)
  <--[internal "context"]-- @19911 next (type: closure, self_size: 28)
    <--[property "next"]-- @19901 RegExp String Iterator (type: object, self_size: 28)
  <--[internal "context"]-- @19903 RegExpStringIterator (type: closure, self_size: 32)
    <--[internal "constructor"]-- @16491 system / Map (type: object shape, self_size: 40)
  <--[internal "context"]-- @19891 MapIterator (type: closure, self_size: 32)
    <--[internal "constructor"]-- @16441 system / Map (type: object shape, self_size: 40)
    <--[internal "constructor"]-- @16439 system / Map (type: object shape, self_size: 40)
    <--[internal "constructor"]-- @16437 system / Map (type: object shape, self_size: 40)
  <--[internal "context"]-- @19861 return (type: closure, self_size: 28)
    <--[property "return"]-- @19853 {next, return} (type: object, self_size: 28)
  <--[internal "context"]-- @19859 next (type: closure, self_size: 28)
    <--[property "next"]-- @19853 {next, return} (type: object, self_size: 28)
  <--[internal "context"]-- @19851 next (type: closure, self_size: 28)
    <--[property "next"]-- @19841 Segmenter String Iterator (type: object, self_size: 28)
  <--[internal "context"]-- @19843 Segment Iterator (type: closure, self_size: 32)
    <--[internal "constructor"]-- @16353 system / Map (type: object shape, self_size: 40)
  <--[internal "context"]-- @19835 [Symbol.iterator] (type: closure, self_size: 28)
    <--[property "<symbol Symbol.iterator>"]-- @19823 {containing, <symbol Symbol.iterator>} (type: object, self_size: 28)
  <--[internal "context"]-- @19833 containing (type: closure, self_size: 28)
    <--[property "containing"]-- @19823 {containing, <symbol Symbol.iterator>} (type: object, self_size: 28)
  <--[internal "context"]-- @19825 Segments (type: closure, self_size: 32)
    <--[internal "constructor"]-- @16347 system / Map (type: object shape, self_size: 40)
  <--[internal "context"]-- @19821 next (type: closure, self_size: 28)
    <--[property "next"]-- @16317 String Iterator (type: object, self_size: 28)
  <--[internal "context"]-- @19813 StringIterator (type: closure, self_size: 32)
    <--[internal "constructor"]-- @16315 system / Map (type: object shape, self_size: 40)
  <--[internal "context"]-- @19811 next (type: closure, self_size: 28)
    <--[property "next"]-- @16309 Set Iterator (type: object, self_size: 28)
  <--[internal "context"]-- @19803 next (type: closure, self_size: 28)
    <--[property "next"]-- @16303 Map Iterator (type: object, self_size: 28)
  <--[internal "context"]-- @19795 return (type: closure, self_size: 28)
    <--[property "return"]-- @16299 Iterator Helper (type: object, self_size: 28)
  <--[internal "context"]-- @19793 next (type: closure, self_size: 28)
    <--[property "next"]-- @16299 Iterator Helper (type: object, self_size: 28)
  <--[internal "context"]-- @19787 next (type: closure, self_size: 28)
    <--[property "next"]-- @16285 Array Iterator (type: object, self_size: 28)
  <--[internal "context"]-- @19779 Array Iterator (type: closure, self_size: 32)
    <--[internal "constructor"]-- @16283 system / Map (type: object shape, self_size: 40)
  <--[internal "context"]-- @19775 throw (type: closure, self_size: 28)
    <--[hidden "0"]-- @19777 system / PropertyArray (type: native, self_size: 20)
    <--[property "throw"]-- @16291 Generator (type: object, self_size: 28)
  <--[internal "context"]-- @19773 return (type: closure, self_size: 28)
    <--[property "return"]-- @16291 Generator (type: object, self_size: 28)
  <--[internal "context"]-- @19771 next (type: closure, self_size: 28)
    <--[property "next"]-- @16291 Generator (type: object, self_size: 28)
  <--[internal "context"]-- @19665 toResizableBuffer (type: closure, self_size: 28)
    <--[hidden "0"]-- @19715 system / PropertyArray (type: native, self_size: 20)
    <--[property "toResizableBuffer"]-- @19705 WebAssembly.Memory (type: object, self_size: 28)
    <--[internal "109"]-- @16273  (type: array, self_size: 4104)
  <--[internal "context"]-- @19663 toFixedLengthBuffer (type: closure, self_size: 28)
    <--[property "toFixedLengthBuffer"]-- @19705 WebAssembly.Memory (type: object, self_size: 28)
    <--[internal "108"]-- @16273  (type: array, self_size: 4104)
  <--[internal "context"]-- @19661 promising (type: closure, self_size: 28)
    <--[hidden "16"]-- @19997 system / PropertyArray (type: native, self_size: 80)
    <--[property "promising"]-- @16553 WebAssembly (type: object, self_size: 12)
    <--[internal "107"]-- @16273  (type: array, self_size: 4104)
  <--[internal "context"]-- @19645  (type: closure, self_size: 32)
    <--[internal "constructor"]-- @20721 system / Map (type: object shape, self_size: 40)
    <--[property "constructor"]-- @20449 EventTarget (type: object, self_size: 28)
    <--[internal "77"]-- @16273  (type: array, self_size: 4104)
  <--[internal "context"]-- @19643  (type: closure, self_size: 32)
    <--[internal "constructor"]-- @20717 system / Map (type: object shape, self_size: 40)
    <--[property "constructor"]-- @20437 EventTarget (type: object, self_size: 28)
    <--[internal "76"]-- @16273  (type: array, self_size: 4104)
  <--[internal "context"]-- @19641  (type: closure, self_size: 32)
    <--[internal "constructor"]-- @20713 system / Map (type: object shape, self_size: 40)
    <--[property "constructor"]-- @20421 EventTarget (type: object, self_size: 28)
    <--[internal "75"]-- @16273  (type: array, self_size: 4104)
  <--[internal "context"]-- @19633 getMessage (type: closure, self_size: 32)
    <--[property "getMessage"]-- @20649 {terminate, terminateAndWait, postMessage, getMessage, …, get onmessage, set onmessage, constructor} (type: object, self_size: 28)
    <--[internal "constructor"]-- @20635 system / Map (type: object shape, self_size: 40)
    <--[property "constructor"]-- @20633 {constructor} (type: object, self_size: 28)
    <--[internal "60"]-- @16273  (type: array, self_size: 4104)
  <--[internal "context"]-- @19631 postMessage (type: closure, self_size: 32)
    <--[property "postMessage"]-- @20649 {terminate, terminateAndWait, postMessage, getMessage, …, get onmessage, set onmessage, constructor} (type: object, self_size: 28)
    <--[internal "constructor"]-- @20621 system / Map (type: object shape, self_size: 40)
    <--[property "constructor"]-- @20619 {constructor} (type: object, self_size: 28)
    <--[internal "59"]-- @16273  (type: array, self_size: 4104)
  <--[internal "context"]-- @19629 terminateAndWait (type: closure, self_size: 32)
    <--[property "terminateAndWait"]-- @20649 {terminate, terminateAndWait, postMessage, getMessage, …, get onmessage, set onmessage, constructor} (type: object, self_size: 28)
    <--[internal "constructor"]-- @20607 system / Map (type: object shape, self_size: 40)
    <--[property "constructor"]-- @20605 {constructor} (type: object, self_size: 28)
    <--[internal "58"]-- @16273  (type: array, self_size: 4104)
  <--[internal "context"]-- @19627 terminate (type: closure, self_size: 32)
    <--[property "terminate"]-- @20649 {terminate, terminateAndWait, postMessage, getMessage, …, get onmessage, set onmessage, constructor} (type: object, self_size: 28)
    <--[internal "constructor"]-- @20597 system / Map (type: object shape, self_size: 40)
    <--[property "constructor"]-- @20595 {constructor} (type: object, self_size: 28)
    <--[internal "57"]-- @16273  (type: array, self_size: 4104)
  <--[internal "context"]-- @19621  (type: closure, self_size: 32)
    <--[internal "constructor"]-- @20785 system / Map (type: object shape, self_size: 40)
    <--[internal "constructor"]-- @20259 system / Map (type: object shape, self_size: 40)
    <--[property "constructor"]-- @20123 {constructor} (type: object, self_size: 28)
    <--[internal "28"]-- @16273  (type: array, self_size: 4104)
  <--[internal "context"]-- @19619 is (type: closure, self_size: 28)
    <--[property "is"]-- @19737 WebAssembly.Exception (type: object, self_size: 28)
    <--[internal "27"]-- @16273  (type: array, self_size: 4104)
  <--[internal "context"]-- @19617 getArg (type: closure, self_size: 28)
    <--[property "getArg"]-- @19737 WebAssembly.Exception (type: object, self_size: 28)
    <--[internal "26"]-- @16273  (type: array, self_size: 4104)
  <--[internal "context"]-- @19615 set value (type: closure, self_size: 28)
    <--[internal "setter"]-- @19727 system / AccessorPair (type: native, self_size: 12)
    <--[property "set value"]-- @19719 WebAssembly.Global (type: object, self_size: 28)
    <--[internal "23"]-- @16273  (type: array, self_size: 4104)
  <--[internal "context"]-- @19613 get value (type: closure, self_size: 28)
    <--[internal "getter"]-- @19727 system / AccessorPair (type: native, self_size: 12)
    <--[property "get value"]-- @19719 WebAssembly.Global (type: object, self_size: 28)
    <--[internal "22"]-- @16273  (type: array, self_size: 4104)
  <--[internal "context"]-- @19611 valueOf (type: closure, self_size: 28)
    <--[property "valueOf"]-- @19719 WebAssembly.Global (type: object, self_size: 28)
    <--[internal "21"]-- @16273  (type: array, self_size: 4104)
  <--[internal "context"]-- @19609 get buffer (type: closure, self_size: 28)
    <--[internal "getter"]-- @19713 system / AccessorPair (type: native, self_size: 12)
    <--[property "get buffer"]-- @19705 WebAssembly.Memory (type: object, self_size: 28)
    <--[internal "19"]-- @16273  (type: array, self_size: 4104)
  <--[internal "context"]-- @19607 grow (type: closure, self_size: 28)
    <--[property "grow"]-- @19705 WebAssembly.Memory (type: object, self_size: 28)
    <--[internal "18"]-- @16273  (type: array, self_size: 4104)
  <--[internal "context"]-- @19605 get (type: closure, self_size: 28)
    <--[hidden "0"]-- @19703 system / PropertyArray (type: native, self_size: 20)
    <--[property "get"]-- @19693 WebAssembly.Table (type: object, self_size: 28)
    <--[internal "16"]-- @16273  (type: array, self_size: 4104)
  <--[internal "context"]-- @19603 set (type: closure, self_size: 28)
    <--[property "set"]-- @19693 WebAssembly.Table (type: object, self_size: 28)
    <--[internal "15"]-- @16273  (type: array, self_size: 4104)
  <--[internal "context"]-- @19601 grow (type: closure, self_size: 28)
    <--[property "grow"]-- @19693 WebAssembly.Table (type: object, self_size: 28)
    <--[internal "14"]-- @16273  (type: array, self_size: 4104)
  <--[internal "context"]-- @19599 get length (type: closure, self_size: 28)
    <--[internal "getter"]-- @19701 system / AccessorPair (type: native, self_size: 12)
    <--[property "get length"]-- @19693 WebAssembly.Table (type: object, self_size: 28)
    <--[internal "13"]-- @16273  (type: array, self_size: 4104)
  <--[internal "context"]-- @19597 get exports (type: closure, self_size: 28)
    <--[internal "getter"]-- @19691 system / AccessorPair (type: native, self_size: 12)
    <--[property "get exports"]-- @19683 WebAssembly.Instance (type: object, self_size: 28)
    <--[internal "11"]-- @16273  (type: array, self_size: 4104)
  <--[internal "context"]-- @19595 customSections (type: closure, self_size: 28)
    <--[hidden "2"]-- @19675 system / PropertyArray (type: native, self_size: 20)
    <--[property "customSections"]-- @16567 Module (type: closure, self_size: 32)
    <--[internal "9"]-- @16273  (type: array, self_size: 4104)
  <--[internal "context"]-- @19593 exports (type: closure, self_size: 28)
    <--[hidden "1"]-- @19675 system / PropertyArray (type: native, self_size: 20)
    <--[property "exports"]-- @16567 Module (type: closure, self_size: 32)
    <--[internal "8"]-- @16273  (type: array, self_size: 4104)
  <--[internal "context"]-- @19591 imports (type: closure, self_size: 28)
    <--[hidden "0"]-- @19675 system / PropertyArray (type: native, self_size: 20)
    <--[property "imports"]-- @16567 Module (type: closure, self_size: 32)
    <--[internal "7"]-- @16273  (type: array, self_size: 4104)
  <--[internal "context"]-- @19589 instantiate (type: closure, self_size: 28)
    <--[hidden "3"]-- @19997 system / PropertyArray (type: native, self_size: 80)
    <--[property "instantiate"]-- @16553 WebAssembly (type: object, self_size: 12)
    <--[internal "5"]-- @16273  (type: array, self_size: 4104)
  <--[internal "context"]-- @19587 validate (type: closure, self_size: 28)
    <--[hidden "2"]-- @19997 system / PropertyArray (type: native, self_size: 80)
    <--[property "validate"]-- @16553 WebAssembly (type: object, self_size: 12)
    <--[internal "4"]-- @16273  (type: array, self_size: 4104)
  <--[internal "context"]-- @19585 compile (type: closure, self_size: 28)
    <--[hidden "1"]-- @19997 system / PropertyArray (type: native, self_size: 80)
    <--[property "compile"]-- @16553 WebAssembly (type: object, self_size: 12)
    <--[internal "3"]-- @16273  (type: array, self_size: 4104)
  <--[internal "context"]-- @19581 Arguments (type: closure, self_size: 32)
    <--[internal "constructor"]-- @16503 system / Map (type: object shape, self_size: 40)
    <--[internal "constructor"]-- @16501 system / Map (type: object shape, self_size: 40)
    <--[internal "constructor"]-- @16499 system / Map (type: object shape, self_size: 40)
    <--[internal "constructor"]-- @16271 system / Map (type: object shape, self_size: 40)
  <--[internal "context"]-- @19575 setContinuationPreservedEmbedderData (type: closure, self_size: 28)
    <--[property "setContinuationPreservedEmbedderData"]-- @16269 {isTraceCategoryEnabled, trace, …, setContinuationPreservedEmbedderData, console} (type: object, self_size: 28)
  <--[internal "context"]-- @19573 getContinuationPreservedEmbedderData (type: closure, self_size: 28)
    <--[property "getContinuationPreservedEmbedderData"]-- @16269 {isTraceCategoryEnabled, trace, …, setContinuationPreservedEmbedderData, console} (type: object, self_size: 28)
  <--[internal "context"]-- @19571 trace (type: closure, self_size: 28)
    <--[property "trace"]-- @16269 {isTraceCategoryEnabled, trace, …, setContinuationPreservedEmbedderData, console} (type: object, self_size: 28)
  <--[internal "context"]-- @19569 isTraceCategoryEnabled (type: closure, self_size: 28)
    <--[property "isTraceCategoryEnabled"]-- @16269 {isTraceCategoryEnabled, trace, …, setContinuationPreservedEmbedderData, console} (type: object, self_size: 28)
  <--[internal "context"]-- @19549 toString (type: closure, self_size: 28)
    <--[hidden "18"]-- @19551 system / PropertyArray (type: native, self_size: 92)
    <--[property "toString"]-- @19497 {constructor, getColumnNumber, getEnclosingColumnNumber, …, isPromiseAll, isToplevel, toString} (type: object, self_size: 28)
  <--[internal "context"]-- @19547 isToplevel (type: closure, self_size: 28)
    <--[hidden "17"]-- @19551 system / PropertyArray (type: native, self_size: 92)
    <--[property "isToplevel"]-- @19497 {constructor, getColumnNumber, getEnclosingColumnNumber, …, isPromiseAll, isToplevel, toString} (type: object, self_size: 28)
  <--[internal "context"]-- @19545 isPromiseAll (type: closure, self_size: 28)
    <--[hidden "16"]-- @19551 system / PropertyArray (type: native, self_size: 92)
    <--[property "isPromiseAll"]-- @19497 {constructor, getColumnNumber, getEnclosingColumnNumber, …, isPromiseAll, isToplevel, toString} (type: object, self_size: 28)
  <--[internal "context"]-- @19543 isNative (type: closure, self_size: 28)
    <--[hidden "15"]-- @19551 system / PropertyArray (type: native, self_size: 92)
    <--[property "isNative"]-- @19497 {constructor, getColumnNumber, getEnclosingColumnNumber, …, isPromiseAll, isToplevel, toString} (type: object, self_size: 28)
  <--[internal "context"]-- @19541 isEval (type: closure, self_size: 28)
    <--[hidden "14"]-- @19551 system / PropertyArray (type: native, self_size: 92)
    <--[property "isEval"]-- @19497 {constructor, getColumnNumber, getEnclosingColumnNumber, …, isPromiseAll, isToplevel, toString} (type: object, self_size: 28)
  <--[internal "context"]-- @19539 isConstructor (type: closure, self_size: 28)
    <--[hidden "13"]-- @19551 system / PropertyArray (type: native, self_size: 92)
    <--[property "isConstructor"]-- @19497 {constructor, getColumnNumber, getEnclosingColumnNumber, …, isPromiseAll, isToplevel, toString} (type: object, self_size: 28)
  <--[internal "context"]-- @19537 isAsync (type: closure, self_size: 28)
    <--[hidden "12"]-- @19551 system / PropertyArray (type: native, self_size: 92)
    <--[property "isAsync"]-- @19497 {constructor, getColumnNumber, getEnclosingColumnNumber, …, isPromiseAll, isToplevel, toString} (type: object, self_size: 28)
  <--[internal "context"]-- @19535 getTypeName (type: closure, self_size: 28)
    <--[hidden "11"]-- @19551 system / PropertyArray (type: native, self_size: 92)
    <--[property "getTypeName"]-- @19497 {constructor, getColumnNumber, getEnclosingColumnNumber, …, isPromiseAll, isToplevel, toString} (type: object, self_size: 28)
  <--[internal "context"]-- @19533 getThis (type: closure, self_size: 28)
    <--[hidden "10"]-- @19551 system / PropertyArray (type: native, self_size: 92)
    <--[property "getThis"]-- @19497 {constructor, getColumnNumber, getEnclosingColumnNumber, …, isPromiseAll, isToplevel, toString} (type: object, self_size: 28)
  <--[internal "context"]-- @19531 getScriptHash (type: closure, self_size: 28)
    <--[hidden "9"]-- @19551 system / PropertyArray (type: native, self_size: 92)
    <--[property "getScriptHash"]-- @19497 {constructor, getColumnNumber, getEnclosingColumnNumber, …, isPromiseAll, isToplevel, toString} (type: object, self_size: 28)
  <--[internal "context"]-- @19529 getScriptNameOrSourceURL (type: closure, self_size: 28)
    <--[hidden "8"]-- @19551 system / PropertyArray (type: native, self_size: 92)
    <--[property "getScriptNameOrSourceURL"]-- @19497 {constructor, getColumnNumber, getEnclosingColumnNumber, …, isPromiseAll, isToplevel, toString} (type: object, self_size: 28)
  <--[internal "context"]-- @19527 getPromiseIndex (type: closure, self_size: 28)
    <--[hidden "7"]-- @19551 system / PropertyArray (type: native, self_size: 92)
    <--[property "getPromiseIndex"]-- @19497 {constructor, getColumnNumber, getEnclosingColumnNumber, …, isPromiseAll, isToplevel, toString} (type: object, self_size: 28)
  <--[internal "context"]-- @19525 getPosition (type: closure, self_size: 28)
    <--[hidden "6"]-- @19551 system / PropertyArray (type: native, self_size: 92)
    <--[property "getPosition"]-- @19497 {constructor, getColumnNumber, getEnclosingColumnNumber, …, isPromiseAll, isToplevel, toString} (type: object, self_size: 28)
  <--[internal "context"]-- @19523 getMethodName (type: closure, self_size: 28)
    <--[hidden "5"]-- @19551 system / PropertyArray (type: native, self_size: 92)
    <--[property "getMethodName"]-- @19497 {constructor, getColumnNumber, getEnclosingColumnNumber, …, isPromiseAll, isToplevel, toString} (type: object, self_size: 28)
  <--[internal "context"]-- @19521 getLineNumber (type: closure, self_size: 28)
    <--[hidden "4"]-- @19551 system / PropertyArray (type: native, self_size: 92)
    <--[property "getLineNumber"]-- @19497 {constructor, getColumnNumber, getEnclosingColumnNumber, …, isPromiseAll, isToplevel, toString} (type: object, self_size: 28)
  <--[internal "context"]-- @19519 getFunctionName (type: closure, self_size: 28)
    <--[hidden "3"]-- @19551 system / PropertyArray (type: native, self_size: 92)
    <--[property "getFunctionName"]-- @19497 {constructor, getColumnNumber, getEnclosingColumnNumber, …, isPromiseAll, isToplevel, toString} (type: object, self_size: 28)
  <--[internal "context"]-- @19517 getFunction (type: closure, self_size: 28)
    <--[hidden "2"]-- @19551 system / PropertyArray (type: native, self_size: 92)
    <--[property "getFunction"]-- @19497 {constructor, getColumnNumber, getEnclosingColumnNumber, …, isPromiseAll, isToplevel, toString} (type: object, self_size: 28)
  <--[internal "context"]-- @19515 getFileName (type: closure, self_size: 28)
    <--[hidden "1"]-- @19551 system / PropertyArray (type: native, self_size: 92)
    <--[property "getFileName"]-- @19497 {constructor, getColumnNumber, getEnclosingColumnNumber, …, isPromiseAll, isToplevel, toString} (type: object, self_size: 28)
  <--[internal "context"]-- @19513 getEvalOrigin (type: closure, self_size: 28)
    <--[hidden "0"]-- @19551 system / PropertyArray (type: native, self_size: 92)
    <--[property "getEvalOrigin"]-- @19497 {constructor, getColumnNumber, getEnclosingColumnNumber, …, isPromiseAll, isToplevel, toString} (type: object, self_size: 28)
  <--[internal "context"]-- @19511 getEnclosingLineNumber (type: closure, self_size: 28)
    <--[property "getEnclosingLineNumber"]-- @19497 {constructor, getColumnNumber, getEnclosingColumnNumber, …, isPromiseAll, isToplevel, toString} (type: object, self_size: 28)
  <--[internal "context"]-- @19509 getEnclosingColumnNumber (type: closure, self_size: 28)
    <--[property "getEnclosingColumnNumber"]-- @19497 {constructor, getColumnNumber, getEnclosingColumnNumber, …, isPromiseAll, isToplevel, toString} (type: object, self_size: 28)
  <--[internal "context"]-- @19507 getColumnNumber (type: closure, self_size: 28)
    <--[property "getColumnNumber"]-- @19497 {constructor, getColumnNumber, getEnclosingColumnNumber, …, isPromiseAll, isToplevel, toString} (type: object, self_size: 28)
  <--[internal "context"]-- @19489 throw (type: closure, self_size: 28)
    <--[hidden "0"]-- @19491 system / PropertyArray (type: native, self_size: 20)
    <--[property "throw"]-- @16295 AsyncGenerator (type: object, self_size: 28)
  <--[internal "context"]-- @19487 return (type: closure, self_size: 28)
    <--[property "return"]-- @16295 AsyncGenerator (type: object, self_size: 28)
  <--[internal "context"]-- @19485 next (type: closure, self_size: 28)
    <--[property "next"]-- @16295 AsyncGenerator (type: object, self_size: 28)
  <--[internal "context"]-- @19439 throw (type: closure, self_size: 28)
    <--[property "throw"]-- @19421 Async-from-Sync Iterator (type: object, self_size: 28)
  <--[internal "context"]-- @19437 return (type: closure, self_size: 28)
    <--[property "return"]-- @19421 Async-from-Sync Iterator (type: object, self_size: 28)
  <--[internal "context"]-- @19435 next (type: closure, self_size: 28)
    <--[property "next"]-- @19421 Async-from-Sync Iterator (type: object, self_size: 28)
  <--[internal "context"]-- @19431 [Symbol.asyncDispose] (type: closure, self_size: 28)
    <--[property "<symbol Symbol.asyncDispose>"]-- @16293 {<symbol Symbol.asyncIterator>, <symbol Symbol.asyncDispose>} (type: object, self_size: 28)
  <--[internal "context"]-- @19429 [Symbol.asyncIterator] (type: closure, self_size: 28)
    <--[property "<symbol Symbol.asyncIterator>"]-- @16293 {<symbol Symbol.asyncIterator>, <symbol Symbol.asyncDispose>} (type: object, self_size: 28)
  <--[internal "context"]-- @19415 transferToFixedLength (type: closure, self_size: 28)
    <--[hidden "1"]-- @19417 system / PropertyArray (type: native, self_size: 20)
    <--[property "transferToFixedLength"]-- @19383 ArrayBuffer (type: object, self_size: 28)
  (1-100 of 874 retainers shown)"#
    );
}

#[test]
fn show_retainers_with_limit() {
    let mut proc = McpProcess::start();
    load_heap1(&mut proc);

    let resp = proc.call_tool(
        2,
        "show_retainers",
        serde_json::json!({ "snapshot_id": 1, "object_id": "@7165", "limit": 1 }),
    );
    let text = get_text(&resp);
    assert_eq!(
        text,
        r#"Object @7165: system / NativeContext (type: native, self_size: 1240, retained_size: 23708)
  <--[weak "value"]-- @21113 system / Cell (type: object shape, self_size: 8)
  (1-1 of 874 retainers shown)"#
    );
}

#[test]
fn show_retainers_with_offset() {
    let mut proc = McpProcess::start();
    load_heap1(&mut proc);

    let resp_all = proc.call_tool(
        2,
        "show_retainers",
        serde_json::json!({ "snapshot_id": 1, "object_id": "@3", "limit": 100 }),
    );
    let text_all = get_text(&resp_all);
    assert_eq!(
        text_all,
        r#"Object @3: (GC roots) (type: synthetic, self_size: 0, retained_size: 128420)
  <--[element "1"]-- @1  (type: synthetic, self_size: 0)"#
    );
}
